name: My second yml file
on: 
    issues:
      types: [opened, edited, closed]
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
    -   name: Output issue information
        run: echo "${{ toJson(github.event) }}"
            